from pymongo import MongoClient
import os

from dotenv import load_dotenv
load_dotenv()

MONGODB_URI = os.getenv('MONGODB_URI')
client = MongoClient(MONGODB_URI)

# MongoDB 클라이언트 생성
DATABASE_NAME = os.getenv('DATABASE_NAME')
db = client[DATABASE_NAME]

NOTICE_DOCUMENT_COLLECTION = os.getenv('NOTICE_DOCUMENT_COLLECTION')
EMBEDDING_VECTOR_COLLECTION = os.getenv('EMBEDDING_VECTOR_COLLECTION')
PDF_DOCUMENT_COLLECTION = os.getenv('PDF_DOCUMENT_COLLECTION')
USER_CHAT_DOCUMENT_COLLECTION = os.getenv('USER_CHAT_DOCUMENT_COLLECTION')

NOTICE_DOCUMENT_COLLECTION = db[NOTICE_DOCUMENT_COLLECTION]
EMBEDDING_VECTOR_COLLECTION = db[EMBEDDING_VECTOR_COLLECTION]
PDF_DOCUMENT_COLLECTION = db[PDF_DOCUMENT_COLLECTION]
USER_CHAT_DOCUMENT_COLLECTION = db[USER_CHAT_DOCUMENT_COLLECTION]